Add initial version of login to Octopus with OIDC or API keys (#3)

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -9,6 +9,11 @@ jobs:
   build:
     runs-on: ubuntu-latest
     name: Build and test
+    permissions:
+      contents: read
+      actions: write
+      checks: write
+      statuses: write
     steps:
       - uses: actions/checkout@v3
 
@@ -23,8 +28,20 @@ jobs:
       - name: Build
         run: npm run build
 
+      - name: Lint
+        run: npm run lint
+
       - name: Test
-        run: npm run test
+        run: npm run ci:test
+
+      - name: Create test report
+        uses: phoenix-actions/test-reporting@v12
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Tests # Name of the check run which will be created
+          path: test-results/jest-*.xml # Path to test results
+          reporter: jest-junit # Format of test results
+          output-to: step-summary
 
       - name: Compare the expected and actual dist/ directories
         run: |
@@ -67,13 +84,3 @@ jobs:
           publish: npm run ci:publish
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-  test:
-    runs-on: ubuntu-latest
-    needs: build
-    name: Test action
-    steps:
-      - uses: actions/checkout@v3
-
-      - name: Run action
-        uses: ./
